version: '3.4'

services:
  clean_architecture.web:
    image: ${DOCKER_REGISTRY-}clean_architecture_web
    container_name: clean_architecture_web
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - clean_architecture.db

  clean_architecture.db:
    image: postgres
    container_name: clean_architecture_db
    environment:
      - POSTGRES_DB=webinar
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123@
    volumes:
      - ./files/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
